name: bubble-visual-hull
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - pyside6
  - tifffile
  - h5py
  - pip
  - pip:
      - openlpt
